- sqlparse/filters.py
- sqlparse/lexer.py
- tests/test_format.py
This is a simple fix for pathological case of empty statement. then stmt.tokens is empty
> Fix pathological case of empty statement

- sqlparse/lexer.py
- tests/test_split.py
Previously if a single quoted string ended with an escaped backslash,
parsing would not consider the string to be terminated.
> Recognize escaped backslashes within strings

- sqlparse/engine/grouping.py
- sqlparse/lexer.py
- sqlparse/sql.py
- sqlparse/tokens.py
- tests/test_parse.py
Fixes #176. I think this is a big improvement over my last attempt in #170.
This gets rid of Punctuation.ArrayIndex (which parsed the entire contents of a square bracket expression as a single token), and returns to parsing [ and ] as generic Punctuation. Instead, it adds a class sql.SquareBrackets, which act essentially identically to sql.Parenthesis. group_parenthesis() is changed to group both parens and square brackets, so Parenthesis and SquareBrackets groups can be nested inside of each other. Finally, SquareBrackets groups are grouped with Names to form Identifiers, so Identifier.get_array_indices() can return the contents of its child SquareBrackets tokens.
> Better square bracket / array index handling

- sqlparse/engine/grouping.py
- sqlparse/sql.py
This should help with https://github.com/andialbrecht/sqlparse/issues/135 and https://github.com/andialbrecht/sqlparse/issues/199. Using the file uploaded to https://github.com/andialbrecht/sqlparse/issues/199, this branch reformats the sql 10x faster:
```
time sqlformat -r ./test.sql -o /dev/null
sqlformat -r ./test.sql -o /dev/null  9.61s user 0.03s system 99% cpu 9.663 total
time sqlformat -r ./test.sql -o /dev/null
sqlformat -r ./test.sql -o /dev/null  0.95s user 0.02s system 99% cpu 0.979 total
```
> Speed up grouping of indentifiers

- sqlparse/engine/grouping.py
Avoid "PendingDeprecationWarning: generator
'group_identifier.<locals>._consume_cycle' raised StopIteration."
Change in Python: https://www.python.org/dev/peps/pep-0479/
> Fix PendingDeprecationWarning on Python 3.5.

- sqlparse/keywords.py
For now, sqlparse does not support 'create sequence' statement. Add keyword 'SEQUENCE' to support it.
> Add keyword 'SEQUENCE'

- sqlparse/keywords.py
- sqlparse/sql.py
- sqlparse/tokens.py
- tests/test_regressions.py
Here's a quick fix for issue #227 which I recently reported.  All of the existing tests still pass and `get_type()` is now correct for my queries.  I'm not 100% happy with the method I used to get the next non-whitespace token...  `self.token_next(self.token_index(...))` seems pretty obtuse.  Is there a better method to use?
> Fix for #227 (get_type() doesn't work for queries that use WITH)

- sqlparse/lexer.py
- tests/test_grouping.py
These were previously caught by (r'[^\W\d_]\w*(?=[.(])', tokens.Name), so I added a special regex just above that one.
> Recognize USING as a keyword in 'USING(', not just in 'USING ('

- sqlparse/engine/grouping.py
in the examples/column_defs_lowlevel.py
```
SQL = """CREATE TABLE foo (
id integer primary key,
title varchar(200) not null,
description text
);"""
```
this example failed to run correctly, because currently `foo (
id integer primary key,
title varchar(200) not null,
description text
)` part will be parsed as a Function, which actually should be parsed as `Identifier('foo')`, `Token(' ')`, `Parenthesis`, separately.
Not all `Identifier Parenthesis` pairs are functions, they may be `CREATE TABLE (...)`,  `varchar (20)` or others, and might not be grouped as Functions.
> CREATE TABLE should not be parsed as Function

- README.rst
- docs/source/index.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- bin/sqlformat
- docs/source/api.rst
- docs/sqlformat.1
- sqlparse/filters.py
- sqlparse/formatter.py
- tests/test_format.py
This pull request adds a new option, `--wrap_after`, which defines a column limit which it'll try not to exceed when printing identifier lists. Instead of printing each identifier in the query on its own line (very annoying for `IN` clauses or `SELECT`s for many columns!), it keeps printing them on the same line until it goes past the `wrap_after` amount, at which point it inserts a newline.
Before:
```
SELECT DISTINCT `foos`.`bar_id`
FROM `foos`
INNER JOIN `bars` ON `bars`.`id` = `foos`.`bar_id`
LEFT JOIN `honks` ON `honks`.foo_id = foos.id
LEFT JOIN `bonks` ON `bonks`.id = `honks`.bonk_id
WHERE `foos`.user_id IN (912034523,
912611173,
912611177,
912611179,
912611191,
912611201,
912611211,
912611397,
912059323,
912096413,
912101453,
912103173,
912106635,
912116235,
912481421,
912482243, …
```
> Add --wrap_after option for wrapping identifier lists.

- sqlparse/keywords.py
- sqlparse/lexer.py
Changes:
+ Alternate form to fix multiline comments - Slight behavior change
+ Refactored re to compile once instead of each time tokenize called
+ Simplified regex strings
+ Added Comment.Hint for Oracle
> Simplify Lexer and Regex

- sqlparse/sql.py
- tests/test_regressions.py
Seemed like this got left behind during all the refactoring
> token_next shouldn't ignore skip_cm argument

- sqlparse/keywords.py
Postgresql has a keyword `RETURNING` used in insert/update/delete commands
> Add RETURNING keyword

- sqlparse/sql.py
- tests/test_grouping.py
Related to #267. Previously with `delete from foo where x > y returning x` the `returning x` part was subsumed into the where clause
> Returning clause ends where clause

- sqlparse/sql.py
- tests/test_tokenize.py
If the value is Single it's already quoted with apostrophes.
Avoid double apostrophes it that case by using double-quotes instead.
For example, if the value is 'value' the output is "'value'" instead of
''value''.
> Avoid double apostrophes

- sqlparse/__init__.py
- sqlparse/cli.py
- sqlparse/compat.py
- sqlparse/filters/output.py
- sqlparse/filters/reindent.py
- sqlparse/lexer.py
- sqlparse/sql.py
- tests/test_parse.py
Working with non-ascii in Python require all-unicode approach, but
string literals in Python 2.7 are bytes and require explicit conversion.
Add tests for non-ascii.
> Convert string literals to unicode using u() for Py27

- .editorconfig
- .travis.yml
- MANIFEST.in
- setup.cfg
- tox.ini
Update various config files.
- Fix Python 3.6 interpreter
- Add Python 3.7 interpreter
- Add Pypy3 to allowed failures
- Update Manifest
- Update editorconfig
- Update pytest ini header
- Make pytest output verbose (iffy on this change)
- Allow tox to pass when interpreters are missing
> Update Config files

- sqlparse/filters/reindent.py
Fixes warning during tests:
PendingDeprecationWarning: generator 'ReindentFilter._flatten_up_to_token' raised StopIteration
PEP 479 documentation: https://www.python.org/dev/peps/pep-0479/
> Fix _flatten_up_to_token() to be PEP 479 compatible

- sqlparse/lexer.py
- tests/test_regressions.py
* Replace default `unicode-escape` in `lexer.py` with `utf-8`;
* Fix `test_parse_sql_with_binary()`, which the digest is actually `iso-8859-1`;
* Add test case for CJK utf-8 test.
Signed-off-by: Tao Wang <twang2218@gmail.com>
> Fix #315 support utf-8 by default

- sqlparse/cli.py
- tests/files/encoding_gbk.sql
- tests/files/encoding_utf8.sql
- tests/test_cli.py
* Add `--encoding` option in CLI with default value 'utf-8'
* Add test case to test format GBK encoded SQL file in CLI
* Make sure input and output are in same encoding.
Signed-off-by: Tao Wang <twang2218@gmail.com>
> Add --encoding option in CLI

- setup.cfg
See:
https://bitbucket.org/pypa/wheel/src/54ddbcc9cec25e1f4d111a142b8bfaa163130a61/wheel/bdist_wheel.py?fileviewer=file-view-default#bdist_wheel.py-119:125
http://pythonwheels.com/
> Rename section to [bdist_wheel] as [wheel] is considered "legacy"

- sqlparse/keywords.py
These are keywords from table options:
CREATE TABLE name (
column definitions,
...
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
> Add more MySQL keywords

- sqlparse/keywords.py
#354 
Fixes error parsing when a name starts with an accented character. Example provided in linked issue.
> Extend alphas with accented characters

- sqlparse/keywords.py
- tests/test_keywords.py
tried to solve one of todo from keywords.py (with creating test_keywords.py script)
added fixme mark for regex that never match.
> adds '1.' option support for float numbers regex

- sqlparse/cli.py
- tests/test_cli.py
Appear as:
```
ResourceWarning: unclosed file ...
```
Always explicitly close files or detach file wrappers.
> Fix unclosed file warnings discovered during tests

- tests/test_regressions.py
Report "ambiguous variable name 'l'", replace with a more descriptive name.
> Fix flake8 warning with newer flake8 version

- sqlparse/cli.py
- sqlparse/filters/reindent.py
- sqlparse/formatter.py
(Note: This is not a finished pull request; specifically, the tests are not passing. If you'd be interested to merge, I can work on those. Thanks for a useful tool.)
This adds a command line argument `--indent_after_first` which sets the
indentation of all lines after the first one, e.g. SELECT, UPDATE, etc. For
example:
$ sqlparse/__main__.py -r sample.sql
UPDATE foo
SET a = 1
WHERE a > 2
AND a < 10;
$ sqlparse/__main__.py -r --indent_after_first sample.sql
UPDATE foo
SET a = 1
WHERE a > 2
AND a < 10;
> Option to indent after first line

- .travis.yml
- CHANGELOG
- setup.py
- tox.ini
Python 3.3 is EOL. It is no longer receiving bug fixes, including for
security issues. Python 3.3 has been EOL since 2017-09-29. For
additional details, see:
https://devguide.python.org/#status-of-python-branches
Additionally, pytest has dropped support for Python 3.3 in a recent
version, causing test failures. See:
https://docs.pytest.org/en/latest/changelog.html#pytest-3-3-0-2017-11-23
> Remove support for EOL Python 3.3

- sqlparse/filters/aligned_indent.py
Issue:  when using `sqlparse` from the command line to parse a sql file with a trailing semicolon with the "reindent_aligned" option, raises `IndexError`.
For instance, given `test.sql`:
```
-- test.sql
select 1;
select 2;
```
The command `$ python -m sqlparse -a test.sql` generates the following stacktrace:
```
$ python -m sqlparse -a test.sql
Traceback (most recent call last):
File "/Users/circld/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/Users/circld/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/circld/miniconda3/lib/python3.6/site-packages/sqlparse/__main__.py", line 22, in <module>
sys.exit(main())
File "/Users/circld/miniconda3/lib/python3.6/site-packages/sqlparse/cli.py", line …
```
> fix trailing semicolon error

- sqlparse/cli.py
- sqlparse/filters/reindent.py
- sqlparse/formatter.py
New format option "indent_columns" [true/false; default: false] to indent all identifiers, including the first one, by indent_width instead of keyword length (a matter of taste, of course):
```
SELECT
name,
rank
FROM wherever
GROUP BY
name
```
I'm not sure this is the right way to implement this. Please advise if you feel it isn't.
> Option: indent all identifiers, including the first one, by width

- sqlparse/filters/reindent.py
- tests/test_format.py
Hi, we'd like to make sure the formatted query is limited to max_width per line (for example, we'd like to embed raw query into python code without break pep8). 
Just wondering if there is any good tool for that (or which cli param should I specify)?
I also noticed the `wrap_after` is not applied to function parameters, this PR is an attempt to fix that.
> Attempt to wrap long function parameters with wrap_after

- sqlparse/engine/grouping.py
- sqlparse/filters/reindent.py
- sqlparse/sql.py
- tests/test_format.py
- tests/test_grouping.py
This patch fixes the formatting on INSERT by creating a new
instance of sql.Values to group all the values.
SQL: insert into foo values (1, 'foo'), (2, 'bar'), (3, 'baz')
Before:
```
insert into foo
values (1,
'foo'), (2,
'bar'), (3,
'baz')
```
After:
```
insert into foo
values (1, 'foo'),
(2, 'bar'),
(3, 'baz')
```
> Fix formatting on INSERT (fixes #329)

- sqlparse/keywords.py
- tests/files/slashcomment.sql
- tests/test_split.py
This could add #456, but doesn't use an optional flag.  Not sure if there's any dialects where double-slashes are used for anything else (floored division like in Python?).
> Add in slash comment functionality

- sqlparse/keywords.py
Adding support for Apache's [Calcite SQL](https://calcite.apache.org/docs/reference.html) additional temporal keywords: `HOUR`, `WEEK`, and `QUARTER`.
> [keywords] Adding Calcite temporal keywords

- sqlparse/filters/aligned_indent.py
- sqlparse/filters/reindent.py
- sqlparse/keywords.py
- sqlparse/sql.py
- tests/test_grouping.py
- tests/test_tokenize.py
Apologies as I'm lacking some historical context but I was wondering why the `GROUP BY` and `ORDER BY` clauses were treated differently than `UNION ALL`, `LEFT JOIN` etc., i.e., being treated as two keywords (`ORDER` and `BY`) rather than one (`ORDER BY`). 
This PR updates the tokenizer to group these keywords together. Note for the aligner I've modified the code so that the aligner is based on the first word (similar to joins) which preserves the current formatting.
> [tokenizer] Grouping GROUP/ORDER BY

- sqlparse/compat.py
- sqlparse/lexer.py
Both Python 2.7 and Python 3 have the type bytes. On Python 2.7, it is
an alias of str, same as was previously defined in compat.py. Makes the
code slightly more compatible with Python 3 style syntax. Observe:
$ python2
>>> bytes
<type 'str'>
> Remove unnecessary compat shim for bytes

- sqlparse/keywords.py
- tests/files/slashcomment.sql
- tests/test_split.py
This reverts commit 170010e7d709f2145169d23482d006dc56856256.
// is not valid in most dialects, so treating it as such should be opt in.
https://github.com/andialbrecht/sqlparse/issues/476
> Revert "Add in slash comment functionality"

- sqlparse/sql.py
This PR fixes an issue where `TokenList()` fails as it's trying to iterate over `tokens` (which is `None`) as opposed to `self.tokens` (which is `[]`).
> [sql] Fix TokenList.__init__ when no tokens are provided

- sqlparse/keywords.py
- tests/test_grouping.py
- tests/test_tokenize.py
This PR addresses #493 by introducing a regex filter to parse the following tokens as comparison operators, rather than keywords: `LIKE`, `ILIKE`, `NOT LIKE`, and `NOT ILIKE`. These terms are regarded as operators by popular SQL engines (e.g. Postgres, MySQL).
@andialbrecht There is a backwards-compatibility consideration here: reclassifying these terms as comparison operators may break preexisting user code that relies on the designation of the terms as keywords. Please let me know what your thoughts are here.
> Parse like and ilike clauses as comparisons

- sqlparse/sql.py
Adding `TIMESTAMP` which is used as a typed literal for a number of SQL dialects including Oracle and Calcite SQL. 
to: @andialbrecht
> [sql] Adding TIMESTAMP to typed literal

- sqlparse/engine/grouping.py
- sqlparse/sql.py
- tests/test_grouping.py
Apologies @andialbrecht I mis interpreted the `M_EXTEND` in #529 as the `TIMESTAMP` should be added to the set of terms which can match the opening of the typed literal.
> [fix] Fixing typed literal regression

- sqlparse/engine/grouping.py
- tests/test_grouping.py
This patch changes the grouping of AS so that:
Foo AS WITH bar AS 1 SELECT 2
with no longer be grouped as:
[Identifier[Foo, AS, WITH, Identifier[Bar AS 1]], SELECT, 2]
but will be grouped as:
[Identifier[Foo], AS, WITH, Identifier[Bar AS 1], SELECT, 2]
This fixes the parsing of CREATE TABLE new_table AS WITH ... so the
rest of the tokens after AS are parsed the same as a bare WITH.
> [grouping] group_as() no longer groups AS CTE

- docs/source/api.rst
I added the explanation about `comma_first` option in `Formatting of SQL Statements` section.
> add comma_first option for docs

- sqlparse/engine/grouping.py
- tests/test_grouping.py
This PR adds the missing `TypedLiteral` type introduced in https://github.com/andialbrecht/sqlparse/pull/513 to the comparison grouping as previously these were being excluded.
```
>>> parse("x > DATE '2020-01-01'")[0]._pprint_tree()                                                                                                     
|- 0 Identifier 'x'
|  `- 0 Name 'x'
|- 1 Whitespace ' '
|- 2 Comparison '>'
|- 3 Whitespace ' '
`- 4 TypedLiteral 'DATE '...'
|- 0 Builtin 'DATE'
|- 1 Whitespace ' '
`- 2 Single ''2020-...'
```
```
>>> parse("x > DATE '2020-01-01'")[0]._pprint_tree() 
`- 0 Comparison 'x > DA...'
|- 0 Identifier 'x'
|  `- 0 Name 'x'
|- 1 Whitespace ' '
|- 2 Comparison '>'
|- 3 Whitespace ' '
`- 4 TypedLiteral 'DATE '...'
|- 0 Builtin 'DATE'
|- 1 Whitespace ' '
`- 2 Single …
```
> [fix] Adding TypedLiteral to comparison

- tox.ini
The Travis configuration does not executed through tox since
f2a3a6ea356dc38e79c4a025217ed8a3875cabac.
> Remove unused pytest-travis-fold test dependency

- sqlparse/keywords.py
- tests/test_tokenize.py
Postgres allows statements of the form:
```sql
SELECT col_1, col_2, SUM(col_3) OVER w
FROM x
WINDOW w AS (PARTITION BY col_1 ORDER BY col_2)
```
where the window is defined once at the end of the query (see [the select documentation](https://www.postgresql.org/docs/9.5/sql-select.html)).
This change adds WINDOW as a postgres keyword, preventing queries like the above being misparsed, with table name and WINDOW being grouped into an single identifier `<Identifier 'x WINDOW'>`.
> Add postgres WINDOW keyword

- sqlparse/sql.py
Partial fix for #621:
In `TokenList._token_matching()` avoid quadratic behavior resulting from taking a slice of `self.tokens` during each invocation.  Since we are working with indexes anyway, just generate the indexes using `range()` and use normal indexing to access the desired tokens instead of calling `enumerate()` with a slice from `self.tokens`.
> Avoid tokens copy

- sqlparse/engine/grouping.py
- tests/test_regressions.py
The `group_tzcasts()` function was including the closing parens, which led the grouping code to afterwards calculate the wrong end token.
This PR will allow Superset to unpin their `sqlparse` version: https://github.com/apache/superset/pull/10165
Fixes #562
> Make tzcast grouping function less eager

- sqlparse/engine/grouping.py
- tests/test_grouping.py
Currently, CREATE TABLE AS SELECT a.k.a. CTAS doesn't parse column aliases with functions e.g., coalesce, if, appropriately.
In the following example, `coalesce` is parsed as `Name` while it should be `Function` to get `get_alias()` appropriately.
```py
>>> import sqlparse
>>> p = sqlparse.parse('CREATE TABLE tbl1 AS SELECT coalesce(t1.col1, 0) AS col1 FROM t1')[0]
>>> p._pprint_tree()
|- 0 DDL 'CREATE'
|- 1 Whitespace ' '
|- 2 Keyword 'TABLE'
|- 3 Whitespace ' '
|- 4 Identifier 'tbl1'
|  `- 0 Name 'tbl1'
|- 5 Whitespace ' '
|- 6 Keyword 'AS'
|- 7 Whitespace ' '
|- 8 DML 'SELECT'
|- 9 Whitespace ' '
|- 10 Identifier 'coales...'
|  |- 0 Name 'coales...'
|  `- 1 Identifier '(t1.co...'
|     |- 0 Parenthesis '(t1.co...'
|     |  |- 0 Punctuation '('
|     |  |- 1 IdentifierList 't1.col...'
| …
```
> CREATE TABLE tbl AS SELECT should return get_alias() for its column

- sqlparse/engine/grouping.py
- tests/test_grouping.py
there were missing `upper()` calls that messed up parsing of some of my create table statements.
Try running the new test without and with my contribution and you will see the bad behavior.
Best,
Simon
> Fixed bad parsing of create table statements that use lower case

- sqlparse/utils.py
Fix #628 
Consider backtick `` ` ``as a quote character and remove it in utils.removte_quotes()
> Add backtick to remove_quotes character list

- docs/source/extending.rst
- docs/source/index.rst
- sqlparse/keywords.py
- sqlparse/lexer.py
- tests/test_keywords.py
- tests/test_parse.py
This PR makes the `Lexer` a singleton class. This object carries the configured syntax as instance attributes. A library user who has non-standard syntax requirements is able to adapt the behavior of the `Lexer` to meet her needs. As an example for how to do this, please see the relevant test:
```python
def test_configurable_syntax():
sql = """select * from foo BACON SPAM EGGS;"""
tokens = sqlparse.parse(sql)[0]
assert list(
(t.ttype, t.value) for t in tokens if t.ttype not in sqlparse.tokens.Whitespace
) == [
(sqlparse.tokens.Keyword.DML, "select"),
(sqlparse.tokens.Wildcard, "*"),
(sqlparse.tokens.Keyword, "from"),
(None, "foo BACON"),
(None, "SPAM EGGS"),
(sqlparse.tokens.Punctuation, ";"),
]
Lexer().add_keywords(
{
"BACON": sqlparse.tokens.Name.Builtin,
"SPAM": …
```
> Configurable syntax

- sqlparse/sql.py
- tests/test_regressions.py
> Fix get_type with comments between WITH keyword

- .github/workflows/codeql-analysis.yml
- .github/workflows/python-app.yml
- pyproject.toml
- tox.ini
In addition, please take care to provide a proper description
on what your change does, fixes or achieves when submitting the 
pull request.
The [second and final Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
See also https://dev.to/hugovk/help-test-python-312-beta-1508/
> Add support for Python 3.12

- CHANGELOG
- sqlparse/keywords.py
- tests/test_parse.py
Fixes #763
Currently string literals using dollar quoting (`$js$mytext$js$`) must be preceded by a whitespace character, which prevents e.g. using `SET application_name=$$foo;bar$$` which is valid PostgreSQL
> allow operators to procede dollar quoted strings

- sqlparse/engine/grouping.py
- tests/test_grouping.py
Fixes https://github.com/andialbrecht/sqlparse/issues/745.
In addition, please take care to provide a proper description
on what your change does, fixes or achieves when submitting the 
pull request.
> Ensure nested ordered identifiers are grouped (fixes #745)

- sqlparse/keywords.py
- sqlparse/lexer.py
This PR adds 2 new dicts to extend sqlparse's lexer: 1 for Snowflake and 1 for BigQuery.
The proposed dicts are not exhaustive, and only add keywords not already covered by existing dicts.
The value of these keywords can be seen when parsing PIVOT or UNPIVOT statements. After this change, PIVOT subqueries are tokenized properly.
Example query to show value:
```
sql = """
WITH SUBSET AS (
SELECT *
FROM DB.SCHEMA.TABLE
WHERE DATE >= '2021-11-15'
),
PIV AS (
SELECT BUCKET, YES, NO, OTHER
FROM (
SELECT BUCKET, AMOUNT, INDICATOR
FROM SUBSET
)
PIVOT ( SUM(AMOUNT) FOR INDICATOR IN ('YES', 'NO', 'OTHER') )
AS p (BUCKET, YES, NO, OTHER)
)
SELECT * FROM PIV
"""
```
> Add snowflake and bigquery keywords

- sqlparse/utils.py
Profiling a `sqlparse.parse()` on a bunch of large `SELECT` queries, 14ms out of 59ms, or ~24% of the time, was spent in `sqlparse.utils.imt()`.
Looking at that function, it did some moving of the `m` and `t` parameters into lists, wasting work when they’re not set or a single element which can use a faster check. To mitigate this, I optimized it to do the check only when the parameters are set, and avoid the listification of single elements.
This doubled its speed, saving 7ms in the same profile.
> Optimize sqlparse.utils.imt().

- sqlparse/engine/grouping.py
- sqlparse/sql.py
- tests/test_grouping.py
Resolves #701 
(N/A) your changes are documented, if needed
Group tokens such as `OVER exist_win` or `OVER (PARTITION BY...)` as the `OVER clause` before grouping `Identifier` and `Function`. Extend tokens of `Function` to include the `OVER clause` if it is next to the `Parenthesis` of function parameters.
> Fixes #701: Add the OVER clause and include it in the Function tokens.

- CHANGELOG
Incorrect PR number was used in changelog. "Support TypedLiterals in get_parameters" was PR #749 not 649.
> Changelog: Fix incorrect PR number
