- CHANGES
- setup.cfg
- sqlparse/__init__.py
As reported at https://github.com/andialbrecht/sqlparse/pull/200#issuecomment-150809416
> Remove universal wheel

- sqlparse/filters.py
> fix issue #213

- sqlparse/keywords.py
> Token keyword correction

- .travis.yml
- pytest.ini
- sqlparse/__init__.py
- sqlparse/engine/__init__.py
- sqlparse/engine/filter.py
- sqlparse/engine/grouping.py
- sqlparse/filters.py
- sqlparse/sql.py
- sqlparse/tokens.py
- tests/test_functions.py
- tests/test_regressions.py
- tox.ini
Change old-style class to new-style
py3 interpreted old code as new-style classes. py2 should match its behavior.
Remove unused hash function.
Update config for travis/tox
> Change old-style class to new-style & remove unused function

- sqlparse/compat.py
- sqlparse/keywords.py
- sqlparse/lexer.py
- tests/test_tokenize.py
Small re-write of `lexer.py`. Surprisingly doesn't change any of the pre-existing behavior; only simplifies the lexing process and removes alot of unnecessary/obscure code.
> Refactor lexer.py

- bin/sqlformat
- sqlparse/filters.py
- sqlparse/formatter.py
- sqlparse/sql.py
- tests/test_format.py
- tests/test_grouping.py
Adds Aligned-Indent Format Filter
Closes #197 as Merged
> Rebased and Updated Aligned-Indent Format

- .travis.yml
- sqlparse/filters/aligned_indent.py
- sqlparse/filters/others.py
- sqlparse/filters/reindent.py
Refactor multiple filters and quiet down travis from spamming with build fail notifications
> Refactor filters

- docs/source/conf.py
- examples/column_defs_lowlevel.py
- examples/extract_table_names.py
- setup.cfg
- setup.py
- sqlparse/engine/grouping.py
- sqlparse/filters/output.py
- sqlparse/filters/reindent.py
- sqlparse/filters/right_margin.py
- sqlparse/formatter.py
- sqlparse/lexer.py
- sqlparse/sql.py
- sqlparse/utils.py
- tests/test_format.py
- tests/test_grouping.py
- tests/test_parse.py
- tests/test_regressions.py
- tests/test_split.py
- tests/test_tokenize.py
Change to new style str-format
Add tests from closed issues.
Add tests from open bugs. 
Add expected fail as Pass
That is, if a bug gets fixed, but the test doesn't get updated to reflect that it was fixed, tests will fail. 
This is to catch accidentally fixing open bugs.
> Add various tests and change to new style str-format

- sqlparse/keywords.py
- sqlparse/lexer.py
Partially reverted the initially fix (tests and CHANGELOG remain untouched)
Added regex solution
> Alternate solution for #277

- README.rst
This PR adds the command to install the sqlparse via PIP.
> Adding pip installation command to README

- sqlparse/filters/reindent.py
- tests/test_regressions.py
https://github.com/andialbrecht/sqlparse/issues/320
> Putting LIMIT on a new line #320

- sqlparse/keywords.py
- tests/test_regressions.py
> CONCURRENTLY should be handled as a keyword

- sqlparse/keywords.py
add PL/pgSQL syntax
(don't mind the commit being a bit old, i made a wrong pull request, and totally forgot about it)
> add PL/pgSQL syntax

- AUTHORS
- CHANGELOG
Just a small change; I go by Pi now. :)
> Update my name in AUTHORS & CHANGELOG

- docs/source/intro.rst
Error: ~sqlarse.format
Collect: ~sqlparse.format
> Fix typo in intro

- sqlparse/keywords.py
- tests/test_split.py
A PR to fix https://github.com/andialbrecht/sqlparse/issues/385
> Fix incorrect splitting with double quotes and a new line

- sqlparse/sql.py
- tests/test_parse.py
A fix for issue https://github.com/andialbrecht/sqlparse/issues/369
> Fix issue with get_real_name returning incorrect name

- sqlparse/sql.py
found this bug while parsing all python strings (ast.Str) from site-packages :)
occurs in psycopg2/tests/test_module.py
> fix "WITH name" case

- sqlparse/sql.py
Added a class named Having and inherited it with TokenList after Where class
It will be easier for further manipulations as a HAVING clause contains multiple conditions just like WHERE clause.
Also made changes in engine->grouping.py
> Added HAVING class

- setup.py
Testing was added in b9ff0bd225e71f4fe522859b49b8194a725b4421.
> Add trove classifier for Python 3.7 support

- sqlparse/keywords.py
- tests/test_format.py
- tests/test_parse.py
This fixes https://github.com/andialbrecht/sqlparse/issues/427
> Fix reindent issue for parenthesis (fixes issue 427)

- sqlparse/filters/others.py
- tests/test_format.py
This fixes https://github.com/andialbrecht/sqlparse/issues/425
> Fix issue with strip_comments causing a syntax error (fixes #425)

- sqlparse/filters/others.py
- tests/test_format.py
Closes https://github.com/andialbrecht/sqlparse/issues/473.
> [filters] Stripping parenthesis whitespace

- docs/source/api.rst
> Update documentation to decrease chance of misunderstandings

- sqlparse/keywords.py
- tests/test_grouping.py
Fixes https://github.com/andialbrecht/sqlparse/issues/507.
> [fix] Addressing issue #507

- sqlparse/keywords.py
- tests/test_grouping.py
> Add regex pattern to identify IN as a Compasion token

- sqlparse/keywords.py
Simply adding RLIKE to show up as a comparison just like LIKE and ILIKE. Current behavior is that it shows up as an identifier.
> Add RLIKE keyword

- sqlparse/keywords.py
As in `INSERT ... ON CONFLICT` https://www.postgresql.org/docs/9.5/sql-insert.html#SQL-ON-CONFLICT
> keyword, add CONFLICT to postgres keywords

- .github/workflows/python-app.yml
"3.10" must be quoted in yaml https://dev.to/hugovk/the-python-3-1-problem-85g
> GitHub Actions: Add Py3.10, update Actions, more flake8 tests

- setup.cfg
A subset of #645 
Follow on to #661
Enhances https://pypi.org/project/sqlparse
> Acknowledge support for Python 3.10

- sqlparse/keywords.py
- tests/test_parse.py
> DIV is Operator

- sqlparse/sql.py
- tests/test_parse.py
In addition, please take care to provide a proper description
on what your change does, fixes or achieves when submitting the 
pull request.
> Support TypedLiterals in get_parameters

- pyproject.toml
In addition, please take care to provide a proper description
on what your change does, fixes or achieves when submitting the 
pull request.
> Fix "Release Notes" link in `pyproject.toml`
